# Generated by Django 4.0.6 on 2022-07-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Useraccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('accountid', models.CharField(max_length=100)),
            ],
        ),
    ]
